all: The-Design-and-Implementation-of-Thunix-Operating-System

The-Design-and-Implementation-of-Thunix-Operating-System: 
	cat  Chapter0-Abstract  Chapter1-Introduction  Chapter2-boot  Chapter3-Protect-Mode  Chapter4-IO-Lib  Chapter5-Interrupt  Chapter6-Driver  Chapter7-File-System > $@ 

clean:
	rm The-Design-and-Implementation-of-Thunix-Operating-System
